### PR TITLE
FIxed mkpath bug, tidied up warnings and fixed handling of spaces in installation paths

### PR DESCRIPTION
**Pull request by ogdenpm**
mkpath bug fixed - CPMDIR80 should now work
Tidied up warnings. Note z80.c just has the warnings about possible loss of accuracy supressed. I do not believe any are worth worrying about.
Fixed the handling of spaces in installation paths.
Minor tweak to xlt_name in that if mixed \ and / are used under windows they are all mapped to / so that directories map to the same auto assigned drive.

### CODE REVIEW

**Comment by ogdenpm** [comment]
Tony
Does your build now work?
I am aware of one issue with Cygwin in that it declares DWORD which conflicts with the one in zxcc.h. probably the best fix is to rename all the DWORD to dword as it also defined.
Longer term converting to use stdint.h would make sure data types were consistent on 64bit builds.
Mark

Regards
Mark
________________________________

**Comment by agn453** [comment]
I'm just about to do a Windows build.  I did have to manually merge the xlt.c file where I'd silenced a macOS CLANG compiler warning - out of sync with your forked version.  I can try a Cygwin build too.  Get back to you shortly.

**Comment by agn453** [comment]
Running the x64 Debug version still reports trying to read the compiler header files from

```
cpmredir trace: fcb_randrd("./testwild.c")
cpmredir trace: Ret: 0x1
cpmredir trace: User: parameter 0 returns 0
cpmredir trace: User: parameter 255 returns 0
cpmredir trace: User: parameter 255 returns 0
cpmredir trace: User: parameter 0 returns 0
cpmredir trace: D:STDIOá  .H
cpmredir trace: fcb_open("d:/local/lib/cpm/include80/stdio.h")
cpmredir trace: Ret: -1
cpmredir trace: User: parameter 0 returns 0
cpmredir trace: User: parameter 255 returns 0
cpmredir trace: User: parameter 255 returns 0
cpmredir trace: User: parameter 0 returns 0
cpmredir trace: @:STDIOá  .H
cpmredir trace: fcb_open("./stdio.h")
cpmredir trace: Ret: -1
cpmredir trace: User: parameter 0 returns 0
P:TESTWILD.C: 12: Can't find include file stdio.h
cpmredir trace: User: parameter 255 returns 0
cpmredir trace: User: parameter 255 returns 0
cpmredir trace: User: parameter 0 returns 0
cpmredir trace: D:CPM  á  .H
cpmredir trace: fcb_open("d:/local/lib/cpm/include80/cpm.h")
cpmredir trace: Ret: -1
```

I have tried with

```
set CPMDIR80=C:\Users\tony\lib\cpm\
```

and

```
set CPMDIR80=
set BINDIR80=C:\Users\tony\lib\cpm\bin80\
set LIBDIR80=C:\Users\tony\lib\cpm\lib80\
set INCDIR80=C:\Users\tony\lib\cpm\include80\
```

and still it looks in ```d:/local/lib/cpm/include80/```

**Comment by ogdenpm** [comment]
Tony

I am not sure what is going on. I rebuilt the code using the source from your github site and it works without problem.

Are you by any chance accidentally picking up an old copy of the executables, particularly zxcc?

One way to check this is to use

where zxcc

to locate the one being used and to delete it. Repeat until it cannot be found then rebuild the debug version and install it.

If you still have a problem, then it may be necessary to use the visual studio debugger to find out what is going on.

 

Regards

Mark

**Comment by ogdenpm** [comment]
Tony

After I had modified the conflicting DWORD definitions, I compiled the code under CYGWIN and it works correctly as well

Regards

Mark

 

 

From: ***@***.*** ***@***.***> 
Sent: 28 December 2021 09:50
To: 'agn453/ZXCC' ***@***.***>
Subject: RE: [agn453/ZXCC] FIxed mkpath bug, tidied up warnings and fixed handling of spaces in installation paths (PR #33)

 

Tony

I am not sure what is going on. I rebuilt the code using the source from your github site and it works without problem.

Are you by any chance accidentally picking up an old copy of the executables, particularly zxcc?

One way to check this is to use

where zxcc

to locate the one being used and to delete it. Repeat until it cannot be found then rebuild the debug version and install it.

If you still have a problem, then it may be necessary to use the visual studio debugger to find out what is going on.

 

Regards

Mark

**Comment by ogdenpm** [comment]
Tony

I think I have found the problem, I was looking in the wrong place.

zxc actually uses the #defined INCDIR80 explicitly, rather than checking for environment variables.

 

Regards

Mark

 

 

From: ***@***.*** ***@***.***> 
Sent: 28 December 2021 10:12
To: 'agn453/ZXCC' ***@***.***>
Subject: RE: [agn453/ZXCC] FIxed mkpath bug, tidied up warnings and fixed handling of spaces in installation paths (PR #33)

 

Tony

After I had modified the conflicting DWORD definitions, I compiled the code under CYGWIN and it works correctly as well

Regards

Mark

 

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: 28 December 2021 09:50
To: 'agn453/ZXCC' ***@***.*** ***@***.***> >
Subject: RE: [agn453/ZXCC] FIxed mkpath bug, tidied up warnings and fixed handling of spaces in installation paths (PR #33)

 

Tony

I am not sure what is going on. I rebuilt the code using the source from your github site and it works without problem.

Are you by any chance accidentally picking up an old copy of the executables, particularly zxcc?

One way to check this is to use

where zxcc

to locate the one being used and to delete it. Repeat until it cannot be found then rebuild the debug version and install it.

If you still have a problem, then it may be necessary to use the visual studio debugger to find out what is going on.

 

Regards

Mark

**Comment by ogdenpm** [comment]
Tony

Modified zxc and issued as pull request, also minor changes to support Cygwin build.

Note Cygwin should still use ./configure. It needs the gnu make to build.

Regards

Mark

 

 

From: ***@***.*** ***@***.***> 
Sent: 28 December 2021 11:33
To: 'agn453/ZXCC' ***@***.***>
Subject: RE: [agn453/ZXCC] FIxed mkpath bug, tidied up warnings and fixed handling of spaces in installation paths (PR #33)

 

Tony

I think I have found the problem, I was looking in the wrong place.

zxc actually uses the #defined INCDIR80 explicitly, rather than checking for environment variables.

 

Regards

Mark

 

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: 28 December 2021 10:12
To: 'agn453/ZXCC' ***@***.*** ***@***.***> >
Subject: RE: [agn453/ZXCC] FIxed mkpath bug, tidied up warnings and fixed handling of spaces in installation paths (PR #33)

 

Tony

After I had modified the conflicting DWORD definitions, I compiled the code under CYGWIN and it works correctly as well

Regards

Mark

 

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: 28 December 2021 09:50
To: 'agn453/ZXCC' ***@***.*** ***@***.***> >
Subject: RE: [agn453/ZXCC] FIxed mkpath bug, tidied up warnings and fixed handling of spaces in installation paths (PR #33)

 

Tony

I am not sure what is going on. I rebuilt the code using the source from your github site and it works without problem.

Are you by any chance accidentally picking up an old copy of the executables, particularly zxcc?

One way to check this is to use

where zxcc

to locate the one being used and to delete it. Repeat until it cannot be found then rebuild the debug version and install it.

If you still have a problem, then it may be necessary to use the visual studio debugger to find out what is going on.

 

Regards

Mark

**Pull request merged**
